apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-reader-sa
  namespace: duckdns-ddns
  # annotations:
  #   argocd.argoproj.io/instance: duckdns-ddns
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: service-reader
  # annotations:
  #   argocd.argoproj.io/instance: duckdns-ddns
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: duckdns-ddns-rbac
  annotations:
    argocd.argoproj.io/instance: duckdns-ddns
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: service-reader-sa
    # Reference to upper's `metadata.namespace`
    namespace: duckdns-ddns
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io