apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.name }}'
  namespace: '{{ .Values.namespace | default .Values.name }}'
  annotations:
    argocd.argoproj.io/instance: '{{ .Values.name }}'
spec:
  selector:
    matchLabels:
      app: '{{ .Values.name }}'
  replicas: 1
  template:
    metadata:
      labels:
        app: '{{ .Values.name }}'
    spec:
      containers:
      - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        # imagePullPolicy: Always
        name: '{{ .Values.name }}'
        ports:
        - containerPort: 80
      # imagePullSecrets:
      # - name: '{{ .Values.image.pullSecret | default "" }}'