apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.name }}'
  namespace: {{ .Values.namespace | default .Values.name }}
  annotations:
    argocd.argoproj.io/instance: '{{ .Values.name }}'
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: '{{ .Values.name }}'